- name: Create VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: kunal_RG
      location: eastus
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: kunal_RG
      name: myVnet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: kunal_RG
      name: mySubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: myVnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: kunal_RG
      allocation_method: Static
      name: myPublicIP
    register: output_ip_address
  - name: Dump public IP for VM which will be created
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: kunal_RG
      name: myNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: kunal_RG
      name: myNIC
      virtual_network: myVnet
      subnet: mySubnet
      public_ip_name: myPublicIP
      security_group: myNetworkSecurityGroup
  - name: Create VM with defaults
    azure_rm_virtualmachine:
      resource_group: kunal_RG
      name: testvm10
      vm_size: Standard_DS1_v2
      admin_username: kunal
      admin_password: Password@1
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.1'
        version: latest


#  - name: Create windows machine
#    azure:
#      name: ben-Winows-23
#      hostname: win123
#      os_type: windows
#      enable_winrm: True
 #    subscription_id: '{{ azure_sub_id }}'
 #    management_cert_path: '{{ azure_cert_path }}'
#      role_size: Small
#      image: bd507d3a70934695bc2128e3e5a255ba__RightImage-Windows-2012-x64-v13.5
#      location: eastus
#      password: 12345
#      storage_account: benooytes
#      user: admin
#      wait: True
#      state: present
#      network_interfaces: myNIC
#      virtual_network_name: '{{ virtual_network: }}'
#      delegate_to: localhost

#  - name: Create VM
#    azure_rm_virtualmachine:
#      resource_group: kunal_RG
#      name: myVM
#      vm_size: Standard_DS1_v2
#      admin_username: azureuser
#      ssh_password_enabled: false
#      ssh_public_keys:
#        - path: /home/ce5dddf9-9c42-4d34-a5db-8c8934c6/.ssh/authorized_keys
#          key_data: ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAsVTNYwZ7EL1xXVUtYO9guhSgJBsLVtD24y1GYEKvVwtV8yJWu0mgKVyzFd7f5uP0523PdCh04WjGn5qkGHtY/wL4x5DU+dr50PIQN4KByVTKnXhTB5kUvqS9lI00eNkQKuMEhnUTJkxhahd8avo128QrnFptS7uK9HKlwhJac+ySivx15wh1bDcLbywtmWl76zu5tY/d59/Nkmu/dF5Z1tmgJiCxoeanDPBLKTg/4fZUoSPxER8615i0WRUZVyXQtaNC1blWcazlgiac0ibUrQyLQ0CZBvgjJujjo6N/89D2VuqPwuNo9FaWkz4IoVOtimh55jOy/JoE7r6HVCY4WQ== rsa-key-20180924
#      network_interfaces: myNIC
#      image:
#        offer: CentOS
#        publisher: OpenLogic
#        sku: '7.5'
#        version: latest
